"""Glossary seeded from terms the agent itself uses in its explanations (PRD 9.3 Glossary panel /
plain-language mode). Definitions are intentionally one line so they can be shown inline on first
encounter ("p99 latency - the response time 99% of requests are faster than")."""

GLOSSARY: list[tuple[str, str, str]] = [
    # (term, one-line definition, category)
    ("p99 latency", "The response time that 99% of requests are faster than; it shows how bad the slowest requests are.", "metrics"),
    ("p95 latency", "The response time that 95% of requests are faster than.", "metrics"),
    ("error rate", "The share (or count per minute) of requests or log lines that ended in an error.", "metrics"),
    ("error velocity", "How fast the number of errors is rising per minute; the first derivative of the error count.", "forecasting"),
    ("error acceleration", "Whether error velocity itself is speeding up; the second derivative. Accelerating errors are a strong warning sign.", "forecasting"),
    ("failure risk score", "A 0-100 estimate of how likely a service is to fail soon. 60+ is a warning, 80+ is critical.", "forecasting"),
    ("baseline", "What 'normal' looks like for a service at this time of day and day of week.", "forecasting"),
    ("baseline deviation", "How far current behaviour is from the service's baseline, measured in standard deviations.", "forecasting"),
    ("pattern drift", "New error types appearing that are related to, but not identical to, earlier errors - a sign a failure mode is forming.", "forecasting"),
    ("leading indicator", "A warning sign that reliably shows up shortly before a failure in this specific system.", "forecasting"),
    ("failure signature", "A fingerprint of the log patterns seen just before a past incident, used to recognise the same build-up again.", "forecasting"),
    ("pre-mortem", "A report describing an incident that is about to happen: why, who is affected and how to prevent it.", "reports"),
    ("post-mortem", "A report written after an incident explaining what happened and how to avoid it next time.", "reports"),
    ("time to impact", "The agent's estimate of how many minutes remain before users are affected.", "forecasting"),
    ("blast radius", "The set of users and services that would be affected if a failure happens.", "reliability"),
    ("MTTR", "Mean time to resolution: the average time from an incident starting to it being fixed.", "reliability"),
    ("SLO", "Service level objective: the reliability target a service promises to meet, e.g. 99.9% of requests succeed.", "reliability"),
    ("RCA", "Root cause analysis: tracing a failure back through related errors to the thing that started it.", "reliability"),
    ("causal chain", "The ordered sequence of failures where each one triggered the next, ending at the root cause.", "reliability"),
    ("root cause", "The original fault that set off the chain of failures, as opposed to the symptoms it caused.", "reliability"),
    ("secondary failure", "An error caused by another failure upstream rather than by a fault in that service itself.", "reliability"),
    ("stack trace", "The list of function calls active when an error happened; read it from the top to find where it broke.", "logs"),
    ("severity", "How serious a log line is: DEBUG, INFO, WARN, ERROR or FATAL, from least to most serious.", "logs"),
    ("DEBUG", "Detailed diagnostic messages for developers; usually noise in production.", "logs"),
    ("INFO", "Normal events, e.g. 'request completed'.", "logs"),
    ("WARN", "Something unexpected that the service handled, but that may need attention.", "logs"),
    ("ERROR", "An operation failed. Worth investigating, especially if it repeats.", "logs"),
    ("FATAL", "The service could not continue. Usually an outage or crash.", "logs"),
    ("trace ID", "An identifier shared by every log line belonging to one request as it crosses services.", "logs"),
    ("request ID", "An identifier for a single request; search it to see everything that happened to that request.", "logs"),
    ("deployment version", "The release of the code that produced the log line; used to spot regressions after a deploy.", "logs"),
    ("regression", "Behaviour that got worse after a change, e.g. a higher error rate after a deployment.", "reliability"),
    ("error cluster", "A group of semantically similar errors, treated as one underlying problem.", "clustering"),
    ("deduplication", "Collapsing repeated identical or near-identical errors into one entry with a count.", "clustering"),
    ("semantic search", "Searching by meaning rather than exact words, using embeddings.", "search"),
    ("embedding", "A list of numbers that captures the meaning of a piece of text so similar texts can be found.", "search"),
    ("keyword search", "Exact text (or regular expression) matching against log messages.", "search"),
    ("anomaly", "Behaviour that is unusual compared with the baseline: a spike, a new error type or a service going quiet.", "anomaly"),
    ("service silence", "A service that normally logs regularly has stopped logging, which can mean it is down.", "anomaly"),
    ("traffic spike", "A sudden jump in the number of requests or log lines.", "anomaly"),
    ("latency spike", "A sudden jump in how long requests take.", "anomaly"),
    ("autonomy tier", "How much the agent may do on its own for a tool: read-only, background, policy-bounded or propose-only.", "agent"),
    ("propose-only", "The agent recommends an action but a human must approve it; it never executes on its own.", "agent"),
    ("recommended action", "A concrete remediation step the agent suggests, such as restarting a worker or scaling a service.", "agent"),
    ("approval queue", "Where actions the agent proposes wait for a human to approve, edit or dismiss them.", "agent"),
    ("guided mode", "A beginner-friendly view that explains terms and reasoning as you go.", "agent"),
    ("PII", "Personally identifiable information such as emails or phone numbers; LogPilot redacts it before storing or sending anywhere.", "security"),
    ("redaction", "Replacing sensitive values (passwords, emails, tokens) with placeholders like [REDACTED_EMAIL].", "security"),
    ("confidence", "How sure the agent is about an answer or prediction, from 0 to 100%.", "agent"),
    ("connection pool", "A limited set of reusable connections to a database or cache; when it runs out, requests start failing.", "infrastructure"),
    ("timeout", "An operation gave up because it took longer than allowed.", "infrastructure"),
    ("circuit breaker", "A safety switch that stops calling a failing dependency so the failure does not spread.", "infrastructure"),
    ("autoscaling", "Automatically adding or removing servers or workers as load changes.", "infrastructure"),
    ("replica", "One running copy of a service or database; more replicas share the load and add resilience.", "infrastructure"),
    ("cascade failure", "A failure in one service that spreads and causes failures in the services that depend on it.", "reliability"),
    ("saturation", "A resource (CPU, memory, connections) is close to fully used.", "infrastructure"),
    ("health state", "The agent's live picture of each service: error rate, top problems and risk.", "agent"),
    ("time-to-incident", "See 'time to impact'.", "forecasting"),
    ("false positive", "An alert that fired although no incident followed.", "forecasting"),
    ("true positive", "An alert that fired and was followed by (or prevented) a real incident.", "forecasting"),
]
